Repository nonebot/nonebot2, pull requests merged in 2020-11, with the labels that each got.

#41 New: 插件广场
  .github/ISSUE_TEMPLATE/plugin-publish.md
  docs/.vuepress/components/Plugins.vue
  docs/.vuepress/public/plugins.json
  docs/api/adapters/cqhttp.md
  docs/api/plugin.md
  docs/api/rule.md
  nonebot/adapters/__init__.py
  nonebot/adapters/cqhttp.py
  nonebot/plugin.py
  nonebot/plugin.pyi
  nonebot/rule.py
  package-lock.json
  package.json
  poetry.lock
Labels: documentation

#42 Fix: Plugin publish template
  .github/ISSUE_TEMPLATE/plugin-publish.md
Labels: bug

#45 New: add pre and post processors (#40)
  docs/api/typing.md
  nonebot/message.py
  nonebot/typing.py
  poetry.lock
Labels: enhancement

#52 Plugin: nonebot-plugin-status
  docs/.vuepress/public/plugins.json
Labels: Plugin

#53 New: add __version__ for nonebot module
  nonebot/__init__.py
Labels: enhancement

#54 Fix: 修复matcher删除逻辑
  docs/api/exception.md
  docs/api/message.md
  docs/api/typing.md
  nonebot/exception.py
  nonebot/message.py
  nonebot/typing.py
Labels: bug

#58 Plugin Haruka Bot
  docs/.vuepress/public/plugins.json
Labels: Plugin

#60 修复阻止事件传递信号无效的问题
  docs/.vuepress/public/plugins.json
  nonebot/message.py
Labels: bug

#63 Plugin: rauthman
  docs/.vuepress/public/plugins.json
  docs/guide/creating-a-handler.md
Labels: Plugin

#64 修复了at机器人时的IndexError
  nonebot/adapters/cqhttp/__init__.py
Labels: bug

#68 Fix: resolve reply message
  nonebot/adapters/cqhttp/__init__.py
Labels: bug

#67 传递matcher抛出的StopPropagation
  nonebot/message.py
Labels: enhancement

#70 Fix: running expired matcher
  nonebot/message.py
Labels: bug

#71 ci: 添加插件议题机器人
  .github/workflows/plugin_issue.yml
Labels: enhancement

#73 Fix: 修复cqhttp相关bug以及plugin export/require支持
  docs/.vuepress/config.js
  docs/api/nonebot.md
  docs/api/plugin.md
  nonebot/__init__.py
  nonebot/adapters/cqhttp/__init__.py
  nonebot/message.py
  nonebot/plugin.py
  nonebot/plugin.pyi
  pages/changelog.md
  tests/bot.py
  tests/test_plugins/test_export.py
Labels: bug, enhancement

#77 Plugin: Sentry日志监控
  docs/.vuepress/public/plugins.json
Labels: Plugin
