Repository nonebot/nonebot2, pull requests merged in 2020-12, with the labels that each got.

#91 Breaking change: remove built-in scheduler support
  docs/.vuepress/config.js
  docs/api/README.md
  docs/api/config.md
  docs/api/sched.md
  docs_build/README.rst
  docs_build/sched.rst
  nonebot/__init__.py
  nonebot/config.py
  nonebot/sched.py
  poetry.lock
  pyproject.toml
Labels: Breaking

#92 Refactor: 更新内置 register_adapter 逻辑
  nonebot/__init__.py
  nonebot/drivers/__init__.py
  nonebot/drivers/fastapi.py
  tests/bot.py
Labels: Breaking

#94 :sparkles: Add ding adapter
  docs/.vuepress/config.js
  docs/api/README.md
  docs/api/adapters/README.md
  docs/api/adapters/cqhttp.md
  docs/api/adapters/ding.md
  docs/api/exception.md
  docs/api/utils.md
  docs_build/README.rst
  docs_build/adapters/cqhttp.rst
  docs_build/adapters/ding.rst
  docs_build/utils.rst
  nonebot/adapters/__init__.py
  nonebot/adapters/cqhttp/__init__.py
  nonebot/adapters/cqhttp/bot.py
  nonebot/adapters/cqhttp/bot.pyi
  nonebot/adapters/cqhttp/event.py
  nonebot/adapters/cqhttp/exception.py
  nonebot/adapters/cqhttp/message.py
  nonebot/adapters/cqhttp/utils.py
  nonebot/adapters/ding/__init__.py
  nonebot/adapters/ding/bot.py
  nonebot/adapters/ding/event.py
  nonebot/adapters/ding/exception.py
  nonebot/adapters/ding/message.py
  nonebot/adapters/ding/model.py
  nonebot/adapters/ding/utils.py
  nonebot/exception.py
  nonebot/typing.py
  nonebot/utils.py
  tests/bot.py
  tests/test_plugins/test_permission.py
Labels: enhancement

#97 New: Add `MatcherGroup` like `CommandGroup`
  docs/api/matcher.md
  docs/api/plugin.md
  nonebot/__init__.py
  nonebot/matcher.py
  nonebot/plugin.py
  nonebot/plugin.pyi
  tests/test_plugins/test_group/__init__.py
  tests/test_plugins/test_group/commands.py
  tests/test_plugins/test_group/matches.py
Labels: enhancement

#100 Plugin: 前端测试机器人插件
  docs/.vuepress/public/plugins.json
Labels: Plugin

#102 Plugin: 定时任务
  docs/.vuepress/public/plugins.json
Labels: Plugin

#103 优化几处文字表达
  docs/.vuepress/public/plugins.json
  docs/guide/installation.md
Labels: documentation

#106 Plugin: 图片搜索
  docs/.vuepress/public/plugins.json
Labels: Plugin

#108 Plugin: 通用数据库连接
  docs/.vuepress/public/plugins.json
Labels: Plugin

#112 Plugin: translator
  docs/.vuepress/public/plugins.json
Labels: Plugin

#115 New: add state factory support
  docs/api/matcher.md
  docs/api/plugin.md
  docs/api/typing.md
  nonebot/matcher.py
  nonebot/plugin.py
  nonebot/plugin.pyi
  nonebot/typing.py
  tests/test_plugins/test_metaevent.py
Labels: enhancement

#123 New: WebSocket Connection Hook
  docs/api/drivers/README.md
  docs/api/typing.md
  nonebot/drivers/__init__.py
  nonebot/drivers/fastapi.py
  nonebot/typing.py
  tests/test_plugins/test_ws_hook.py
Labels: enhancement

#124 📝 Add scheduler.md
  docs/advanced/scheduler.md
Labels: documentation

#125 typo fixed
  docs/.vuepress/public/plugins.json
  docs/guide/creating-a-plugin.md
Labels: documentation
