Repository nonebot/nonebot2, pull requests merged in 2021-02, with the labels that each got.

#182 Plugin: 风格化字符串管理
  docs/.vuepress/public/plugins.json
Labels: Plugin

#179 New: 添加 mirai-api-http 的 adapter 支持
  README.md
  docs/.vuepress/config.js
  docs/api/README.md
  docs/api/adapters/mirai.md
  docs/guide/getting-started.md
  docs/guide/mirai-guide.md
  docs_build/README.rst
  docs_build/adapters/mirai.rst
  nonebot/adapters/mirai/LICENSE
  nonebot/adapters/mirai/__init__.py
  nonebot/adapters/mirai/bot.py
  nonebot/adapters/mirai/bot_ws.py
  nonebot/adapters/mirai/config.py
  nonebot/adapters/mirai/event/__init__.py
  nonebot/adapters/mirai/event/base.py
  nonebot/adapters/mirai/event/message.py
  nonebot/adapters/mirai/event/meta.py
  nonebot/adapters/mirai/event/notice.py
  nonebot/adapters/mirai/event/request.py
  nonebot/adapters/mirai/message.py
  nonebot/adapters/mirai/utils.py
  poetry.lock
  pyproject.toml
  tests/.env.dev
  tests/bot.py
  tests/test_plugins/test_mirai.py
Labels: enhancement

#186 Feat:Support shell-like command
  docs/.vuepress/public/plugins.json
  docs/api/exception.md
  docs/api/nonebot.md
  docs/api/plugin.md
  docs/api/rule.md
  nonebot/__init__.py
  nonebot/exception.py
  nonebot/plugin.py
  nonebot/plugin.pyi
  nonebot/rule.py
  tests/test_plugins/test_shell.py
Labels: enhancement

#188 Docs: 优化文档语言表达
  docs/.vuepress/config.js
  docs/.vuepress/public/manifest.json
  docs/README.md
  docs/advanced/runtime-hook.md
  docs/advanced/scheduler.md
  docs/guide/README.md
  docs/guide/basic-configuration.md
  docs/guide/creating-a-project.md
  docs/guide/ding-guide.md
  docs/guide/getting-started.md
  docs/guide/installation.md
  docs/guide/mirai-guide.md
Labels: documentation

#193 Fix: `MatcherGroup` rule override
  docs/api/plugin.md
  nonebot/plugin.py
  nonebot/plugin.pyi
Labels: bug

#195 Bug: 修复由于消息未转义导致的日志出错
  nonebot/adapters/mirai/utils.py
Labels: bug

#197 Docs: update export-and-require doc
  docs/advanced/export-and-require.md
Labels: documentation

#196 New: 添加一个使用Quart的Driver
  .github/workflows/build_docs.yml
  docs/.vuepress/config.js
  docs/api/README.md
  docs/api/drivers/quart.md
  docs_build/README.rst
  docs_build/drivers/quart.rst
  nonebot/drivers/quart.py
  poetry.lock
  pyproject.toml
  tests/.env.dev
Labels: enhancement

#199 Bug: 修复在Mirai中命令匹配无效的Bug
  nonebot/adapters/mirai/bot.py
  nonebot/adapters/mirai/event/__init__.py
  nonebot/adapters/mirai/event/message.py
  nonebot/adapters/mirai/message.py
  nonebot/adapters/mirai/utils.py
  nonebot/matcher.py
  nonebot/plugin.py
  nonebot/rule.py
  tests/test_plugins/test_mirai.py
Labels: bug

#200 Docs: 错别字
  docs/api/adapters/mirai.md
  docs/guide/creating-a-matcher.md
Labels: documentation

#201 Hotfix: error module name for plugin wordbank
  docs/.vuepress/public/plugins.json
Labels: bug

#204 Update docs for 2.0.0a10
  archive/2.0.0a10/README.md
  archive/2.0.0a10/advanced/README.md
  archive/2.0.0a10/advanced/export-and-require.md
  archive/2.0.0a10/advanced/overloaded-handlers.md
  archive/2.0.0a10/advanced/permission.md
  archive/2.0.0a10/advanced/publish-plugin.md
  archive/2.0.0a10/advanced/runtime-hook.md
  archive/2.0.0a10/advanced/scheduler.md
  archive/2.0.0a10/api/README.md
  archive/2.0.0a10/api/adapters/README.md
  archive/2.0.0a10/api/adapters/cqhttp.md
  archive/2.0.0a10/api/adapters/ding.md
  archive/2.0.0a10/api/adapters/mirai.md
  archive/2.0.0a10/api/config.md
  archive/2.0.0a10/api/drivers/README.md
  archive/2.0.0a10/api/drivers/fastapi.md
  archive/2.0.0a10/api/drivers/quart.md
  archive/2.0.0a10/api/exception.md
  archive/2.0.0a10/api/log.md
  archive/2.0.0a10/api/matcher.md
  archive/2.0.0a10/api/message.md
  archive/2.0.0a10/api/nonebot.md
  archive/2.0.0a10/api/permission.md
  archive/2.0.0a10/api/plugin.md
  archive/2.0.0a10/api/rule.md
  archive/2.0.0a10/api/typing.md
  archive/2.0.0a10/api/utils.md
  archive/2.0.0a10/guide/README.md
  archive/2.0.0a10/guide/basic-configuration.md
  archive/2.0.0a10/guide/cqhttp-guide.md
  archive/2.0.0a10/guide/creating-a-handler.md
  archive/2.0.0a10/guide/creating-a-matcher.md
  archive/2.0.0a10/guide/creating-a-plugin.md
  archive/2.0.0a10/guide/creating-a-project.md
  archive/2.0.0a10/guide/ding-guide.md
  archive/2.0.0a10/guide/end-or-start.md
  archive/2.0.0a10/guide/getting-started.md
  archive/2.0.0a10/guide/installation.md
  archive/2.0.0a10/guide/loading-a-plugin.md
  archive/2.0.0a10/guide/mirai-guide.md
  archive/2.0.0a10/sidebar.config.json
  archive/2.0.0a9.post1/advanced/export-and-require.md
  docs/.vuepress/versions.json
Labels: documentation

#206 Update Docs
  README.md
  docs/advanced/export-and-require.md
  docs/advanced/permission.md
  docs/advanced/runtime-hook.md
  docs/advanced/scheduler.md
Labels: documentation

#208 Plugin: Arcaea 查分器
  docs/.vuepress/public/plugins.json
Labels: Plugin

#210 Plugin: hk-reporter
  docs/.vuepress/public/plugins.json
Labels: Plugin

#211 Doc: use github action instead of netlify ci/cd
  .github/workflows/site_deploy.yml
Labels: documentation

#214 Plugin: 网易云无损音乐下载
  docs/.vuepress/public/plugins.json
Labels: Plugin

#215 Fix: `nonebot-plugin-ncm` repo link error
  docs/.vuepress/public/plugins.json
Labels: documentation

#217 Docs: 添加 从IDE启动的相关问题 提示
  docs/.vuepress/public/plugins.json
  docs/guide/creating-a-project.md
Labels: documentation

#218 Breaking: change nonebot project structure
  .github/ISSUE_TEMPLATE/adapter-publish.md
  .github/ISSUE_TEMPLATE/plugin-publish.md
  .github/workflows/site_deploy.yml
  README.md
  docs/.vuepress/public/adapters.json
  docs/api/adapters/README.md
  docs/api/nonebot.md
  docs/guide/creating-a-project.md
  nonebot/adapters/__init__.py
  packages/nonebot-adapter-cqhttp/README.md
  packages/nonebot-adapter-cqhttp/nonebot/__init__.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/__init__.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/__init__.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.pyi
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/config.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/event.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/exception.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/message.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/permission.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/utils.py
  packages/nonebot-adapter-cqhttp/poetry.lock
  packages/nonebot-adapter-cqhttp/pyproject.toml
  packages/nonebot-adapter-ding/README.md
  packages/nonebot-adapter-ding/nonebot/__init__.py
  packages/nonebot-adapter-ding/nonebot/adapters/__init__.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/__init__.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/config.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/event.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/exception.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/message.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/utils.py
  packages/nonebot-adapter-ding/poetry.lock
  packages/nonebot-adapter-ding/pyproject.toml
  packages/nonebot-adapter-mirai/LICENSE
  packages/nonebot-adapter-mirai/README.md
  packages/nonebot-adapter-mirai/nonebot/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot_ws.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/config.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/base.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/message.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/meta.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/notice.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/request.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/utils.py
  packages/nonebot-adapter-mirai/poetry.lock
  packages/nonebot-adapter-mirai/pyproject.toml
  packages/nonebot-plugin-docs/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: Breaking, enhancement

#226 Update installation.md
  archive/2.0.0a10/guide/installation.md
Labels: documentation

#230 Plugin: nonebot-plugin-cocdicer
  docs/.vuepress/public/plugins.json
Labels: Plugin

#231 Fix: site deploy ci
  .github/workflows/site_deploy.yml
  archive/2.0.0a10/guide/installation.md
  nonebot/__init__.py
Labels: documentation

#233 Plugin: 跑团记录记录器
  docs/.vuepress/public/plugins.json
Labels: Plugin

#243 Bug: adapter can be register more than once
  nonebot/drivers/__init__.py
Labels: bug

#245 Plugin: nonebot-plugin-r6s
  docs/.vuepress/public/plugins.json
Labels: Plugin

#246 Docs: 添加 Vercel 文档镜像链接
  README.md
Labels: documentation

#249 Plugin: 猜猜看
  docs/.vuepress/public/plugins.json
Labels: Plugin
