Repository nonebot/nonebot2, pull requests merged in 2021-03, with the labels that each got.

#251 Plugin: 例：缩写查询器
  docs/.vuepress/public/plugins.json
Labels: Plugin

#255 Fix: prompt type error
  docs/api/adapters/README.md
  docs/api/adapters/cqhttp.md
  docs/api/adapters/ding.md
  docs/api/adapters/mirai.md
  nonebot/adapters/_base.py
  nonebot/matcher.py
Labels: bug

#259 Plugin: biliav小程序转换器
  docs/.vuepress/public/plugins.json
  docs/api/nonebot.md
Labels: Plugin

#261 Fix: fix adapter override namespace file
  packages/nonebot-adapter-cqhttp/pyproject.toml
  packages/nonebot-adapter-ding/pyproject.toml
  packages/nonebot-adapter-mirai/pyproject.toml
Labels: bug

#262 Fix: exclude all `__init__.py` in adapter packaging
  packages/nonebot-adapter-cqhttp/pyproject.toml
  packages/nonebot-adapter-ding/pyproject.toml
  packages/nonebot-adapter-mirai/pyproject.toml
Labels: bug

#265 ci: 更新商店发布议题机器人
  .github/workflows/plugin_issue.yml
Labels: documentation

#267 Plugin: 插件管理器
  docs/.vuepress/public/plugins.json
Labels: Plugin

#270 Bug: correct params order
  .github/workflows/plugin_issue.yml
  docs/.vuepress/components/Plugin.vue
  docs/.vuepress/public/plugins.json
Labels: documentation

#268 Docs: 添加对分离适配器的提示
  docs/api/drivers/fastapi.md
  docs/guide/cqhttp-guide.md
  docs/guide/ding-guide.md
  docs/guide/installation.md
  docs/guide/mirai-guide.md
Labels: documentation

#278 Bot: HarukaBot
  docs/.vuepress/public/bots.json
Labels: Bot

#280 Bot: Omega Miya
  docs/.vuepress/public/bots.json
Labels: Bot

#281 Fix: store bot display error
  README.md
  docs/.vuepress/components/Bot.vue
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/request.py
  tests/.env
Labels: documentation

#285 Docs: 在2.0.0a11文档中添加分离适配器的提示
  archive/2.0.0a11/guide/cqhttp-guide.md
  archive/2.0.0a11/guide/ding-guide.md
  archive/2.0.0a11/guide/installation.md
  archive/2.0.0a11/guide/mirai-guide.md
  docs/.vuepress/public/bots.json
Labels: documentation

#287 Plugin: bilibili视频、番剧解析
  docs/.vuepress/public/plugins.json
Labels: Plugin

#276 统一adapters中MessageEvent get_session_id方法返回的内容
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/event.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/event.py
Labels: Breaking

#292 Plugin: 本地数据存储
  docs/.vuepress/public/plugins.json
Labels: Plugin

#293 Docs: 修正文档中钩子函数的参数
  archive/2.0.0a11/advanced/runtime-hook.md
  docs/advanced/runtime-hook.md
  docs/api/plugin.md
Labels: documentation

#294 Docs: update hook docs
  docs/advanced/README.md
  docs/advanced/runtime-hook.md
Labels: documentation

#300 修复单独被@报错问题，以及使机器人可以判断出在消息任意位置的@信息
  docs/.vuepress/public/plugins.json
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/utils.py
Labels: bug

#307 New: add call_api hook
  docs/api/adapters/README.md
  docs/api/adapters/ding.md
  nonebot/adapters/_base.py
  nonebot/typing.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.pyi
  packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
Labels: enhancement
