Repository nonebot/nonebot2, pull requests merged in 2021-06, with the labels that each got.

#403 Bot: YanXiBot
  docs/.vuepress/public/bots.json
Labels: Bot

#405 Bot: 绪山真寻bot
  docs/.vuepress/public/bots.json
Labels: Bot

#407 修复Mirai加群通过时报错
  docs/.vuepress/public/bots.json
  docs/.vuepress/public/plugins.json
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/request.py
Labels: bug

#406 Feature: 支持自定义 Response
  docs/api/adapters/README.md
  docs/api/adapters/cqhttp.md
  docs/api/adapters/ding.md
  docs/api/adapters/mirai.md
  docs/api/drivers/README.md
  docs/api/drivers/fastapi.md
  docs/api/drivers/quart.md
  docs/api/exception.md
  nonebot/adapters/_base.py
  nonebot/drivers/__init__.py
  nonebot/drivers/fastapi.py
  nonebot/drivers/quart.py
  nonebot/exception.py
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/bot.py
  packages/nonebot-adapter-ding/nonebot/adapters/ding/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot_ws.py
Labels: Breaking, enhancement

#409 Docs: typo
  docs/api/adapters/README.md
  docs/api/adapters/cqhttp.md
  docs/api/adapters/ding.md
  docs/api/adapters/mirai.md
  docs/api/drivers/README.md
  nonebot/drivers/__init__.py
  nonebot/drivers/quart.py
Labels: documentation

#410 修复shell_command多次--help时重复输出
  docs/api/adapters/README.md
  docs/api/adapters/ding.md
  docs/api/adapters/mirai.md
  docs/api/drivers/quart.md
  nonebot/rule.py
Labels: bug

#412 Plugin: nonebot_plugin_pixivrank_search
  docs/.vuepress/public/plugins.json
Labels: Plugin

#416 Plugin: nonebot_plugin_russian
  docs/.vuepress/public/plugins.json
Labels: Plugin

#419 New: get_bot function
  docs/api/config.md
  docs/api/drivers/README.md
  docs/api/nonebot.md
  nonebot/__init__.py
Labels: enhancement

#421 Docs: fix typo
  docs/guide/creating-a-handler.md
Labels: documentation
