Repository nonebot/nonebot2, pull requests merged in 2021-01, with the labels that each got.

#131 Fix: Group event parse error
  nonebot/adapters/cqhttp/event.py
Labels: bug

#132 ✏️ Fix typo
  docs/guide/creating-a-handler.md
  docs/guide/creating-a-matcher.md
Labels: documentation

#135 fix incorrect removing temp matcher
  nonebot/message.py
Labels: bug

#137 fix cqhttp message type guess
  nonebot/adapters/cqhttp/bot.py
Labels: bug

#143 Fix typo
  docs/api/config.md
  nonebot/config.py
Labels: documentation

#149 add fastapi driver configs
  nonebot/drivers/fastapi.py
Labels: enhancement

#160 Plugin: 模拟抽卡
  docs/.vuepress/public/plugins.json
Labels: Plugin

#164 Plugin: nonebot-plugin-wordbank
  docs/.vuepress/public/plugins.json
Labels: Plugin

#166 New: common config loading from .env
  docs/api/config.md
  docs/api/plugin.md
  docs/guide/basic-configuration.md
  nonebot/__init__.py
  nonebot/config.py
  tests/.env
Labels: enhancement

#168 Plugin: 冷却事件
  docs/.vuepress/public/plugins.json
Labels: Plugin

#173 Plugin: mqtt接入
  docs/.vuepress/public/plugins.json
Labels: Plugin

#175 Plugin: 消息交互式 python 解释器
  docs/.vuepress/public/plugins.json
Labels: Plugin

#178 Plugin: songpicker2
  docs/.vuepress/public/plugins.json
Labels: Plugin
