Repository nonebot/nonebot2, pull requests merged in 2021-10, with the labels that each got.

#545 Feature: support use `Message` object as message template
  docs/api/adapters/README.md
  nonebot/adapters/_message.py
  nonebot/adapters/_template.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py
Labels: enhancement

#546 Feature: Add support for mirai adapter `NudgeEvent`
  docs/api/adapters/mirai.md
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/base.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/notice.py
Labels: enhancement

#555 Feature: support use `MessageSegment` factory method as message template format spec
  docs/api/adapters/README.md
  nonebot/adapters/_message.py
  nonebot/adapters/_template.py
Labels: enhancement

#556 Fix: fix cqhttp MessageSegment bugs
  packages/nonebot-adapter-cqhttp/nonebot/adapters/cqhttp/message.py
Labels: bug

#557 Feature: template support raw string
  docs/api/adapters/README.md
  nonebot/adapters/_message.py
  nonebot/adapters/_template.py
  pages/changelog.md
Labels: enhancement, Breaking

#578 Plugin: leetcode提醒机器人
  docs/.vuepress/public/plugins.json
Labels: Plugin
