Repository nonebot/nonebot2, pull requests merged in 2021-05, with the labels that each got.

#344 Docs: update loading-a-plugin docs
  docs/guide/loading-a-plugin.md
Labels: documentation

#349 Adapter: gocq
  docs/.vuepress/public/adapters.json
Labels: Adapter

#350 Docs: fix store link
  archive/2.0.0a10/advanced/scheduler.md
  archive/2.0.0a13.post1/advanced/scheduler.md
  archive/2.0.0a8.post2/advanced/scheduler.md
  docs/advanced/scheduler.md
  docs/guide/installation.md
Labels: documentation

#356 Plugin: Minecraft 服务器状态查询
  docs/.vuepress/public/plugins.json
Labels: Plugin

#359 [Doc] Update: CQHTTP implementations rename
  docs/api/matcher.md
  docs/guide/cqhttp-guide.md
Labels: documentation

#360 Docs: 添加中国大陆文档镜像
  README.md
Labels: documentation

#362 Plugin: Nonebot2插件轻量帮助列表
  docs/.vuepress/public/plugins.json
Labels: Plugin

#364 Plugin: nonebot_plugin_gamedraw
  docs/.vuepress/public/plugins.json
Labels: Plugin

#366 Docs: update permission doc
  docs/advanced/overloaded-handlers.md
  docs/advanced/permission.md
  docs/guide/loading-a-plugin.md
Labels: documentation

#371 Plugin: nonebot-plugin-alias
  docs/.vuepress/public/plugins.json
Labels: Plugin

#374 更新 Mirai-API-HTTP 用户指南
  docs/guide/mirai-guide.md
Labels: documentation

#378 Docs: Add mirai adapter port config
  docs/.vuepress/public/adapters.json
  docs/.vuepress/public/bots.json
  docs/.vuepress/public/plugins.json
  docs/guide/mirai-guide.md
Labels: documentation

#377 Docs: Readme.md 增加 awesome-nonebot 资源库
  README.md
Labels: documentation

#382 Plugin: Nonebot2 消息撤回插件
  docs/.vuepress/public/plugins.json
Labels: Plugin

#386 typo
  docs/api/adapters/README.md
  nonebot/matcher.py
Labels: documentation

#391 Docs: add discord server link
  README.md
  docs/api/drivers/README.md
Labels: documentation
