Repository nonebot/nonebot2, pull requests merged in 2021-04, with the labels that each got.

#309 Fix: matcher got recursion
  nonebot/matcher.py
Labels: bug

#314 Docs: 优化文档商店页显示效果
  .prettierrc
  docs/.vuepress/components/Adapter.vue
  docs/.vuepress/components/Bot.vue
  docs/.vuepress/components/Messenger.vue
  docs/.vuepress/components/Plugin.vue
  docs/.vuepress/components/PublishCard.vue
  docs/.vuepress/components/Store.vue
  docs/advanced/permission.md
  docs/advanced/scheduler.md
  docs/api/plugin.md
  docs/api/rule.md
  docs/guide/creating-a-project.md
  docs/guide/ding-guide.md
  package.json
Labels: documentation

#316 Docs: 写明所需 Python 最低版本小版本号
  README.md
Labels: documentation

#319 Docs: 更新 go-cqhttp 配置文件
  docs/guide/cqhttp-guide.md
Labels: documentation

#322 为`handle_event`函数添加异常返回
  nonebot/message.py
Labels: enhancement

#328 Docs: 文档优化
  docs/guide/creating-a-plugin.md
  docs/guide/installation.md
Labels: documentation

#330 Plugin: 待办事项提醒（闹钟）
  docs/.vuepress/public/plugins.json
Labels: Plugin

#331 Docs: 一点小修改
  docs/guide/installation.md
Labels: documentation

#334 Fix: log module name error
  nonebot/log.py
  nonebot/plugin/manager.py
Labels: bug

#336 Docs: update handlers overload doc
  docs/.vuepress/public/bots.json
  docs/.vuepress/public/plugins.json
  docs/advanced/overloaded-handlers.md
Labels: documentation

#338 Bot: Github Bot
  docs/.vuepress/public/bots.json
Labels: Bot

#343 Plugin: nonebot_plugin_puppet
  docs/.vuepress/public/plugins.json
Labels: Plugin
