Repository nonebot/nonebot2, pull requests merged in 2021-08, with the labels that each got.

#461 Add forward driver support for mirai-api-http adapter
  docs/api/adapters/mirai.md
  docs_build/adapters/mirai.rst
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/__init__.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot_ws.py
Labels: enhancement

#464 Docs: update guide docs
  archive/2.0.0a14/guide/cqhttp-guide.md
  archive/2.0.0a14/guide/mirai-guide.md
  docs/guide/cqhttp-guide.md
  docs/guide/mirai-guide.md
Labels: documentation

#466 Bot: DicePP
  docs/.vuepress/public/bots.json
Labels: Bot

#468 Plugin: 和风天气
  docs/.vuepress/public/plugins.json
Labels: Plugin

#471 Fix log tag escape error in `event.get_description` in mirai adapter
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/event/base.py
Labels: bug

#476 Plugin: nonebot-plugin-autohelp
  docs/.vuepress/public/plugins.json
Labels: Plugin

#481 Plugin: 孤寡机器人
  docs/.vuepress/public/plugins.json
Labels: Plugin

#483 Plugin: 布谷机器人
  docs/.vuepress/public/plugins.json
Labels: Plugin

#485 Plugin: nonebot-plugin-flexperm
  docs/.vuepress/public/plugins.json
Labels: Plugin

#489 Bugfix: remove mirai session expiry
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
Labels: bug

#491 bugfix: catch setup factory exception
  nonebot/drivers/aiohttp.py
  nonebot/drivers/fastapi.py
Labels: bug

#492 feature: mirai multiple accounts support
  docs/guide/mirai-guide.md
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/bot.py
Labels: enhancement

#495 添加设置项，使得可以切换飞书和Lark API地址
  docs/.vuepress/public/bots.json
  docs/.vuepress/public/plugins.json
  docs/api/adapters/feishu.md
  packages/nonebot-adapter-feishu/nonebot/adapters/feishu/bot.py
  packages/nonebot-adapter-feishu/nonebot/adapters/feishu/config.py
Labels: enhancement

#499 Plugin: Epic 限免游戏资讯
  docs/.vuepress/public/plugins.json
Labels: Plugin

#501 Plugin: ELF_RSS
  docs/.vuepress/public/plugins.json
Labels: Plugin

#503 Fix exception raised when constructing `MessageChain` from string
  packages/nonebot-adapter-mirai/nonebot/adapters/mirai/message.py
Labels: bug

#507 Bot: SetuBot
  docs/.vuepress/public/bots.json
Labels: Bot

#510 Feature: `str.format` like message formatting support
  docs/api/adapters/README.md
  docs_build/adapters/README.rst
  nonebot/adapters/_base.py
  nonebot/adapters/_formatter.py
Labels: enhancement

#514 🐛 Fix endswith match bug
  nonebot/rule.py
Labels: bug
