Repository nonebot/nonebot2, pull requests merged in 2022-02, with the labels that each got.

#760 Plugin: nonebot-plugin-setu2
  website/static/plugins.json
Labels: Plugin

#762 Plugin: random-cat
  website/static/plugins.json
Labels: Plugin

#767 Plugin: 群聊反闪照
  website/static/plugins.json
Labels: Plugin

#765 Docs: update some advanced docs
  nonebot/drivers/fastapi.py
  website/docs/advanced/README.md
  website/docs/advanced/di/dependency-injection.md
  website/docs/advanced/di/overload.md
  website/docs/advanced/export-and-require.md
  website/docs/advanced/images/Handle-Event.png
  website/docs/advanced/permission.md
  website/docs/advanced/runtime-hook.md
Labels: documentation

#771 Feature: refactor and support bot connection hook
  nonebot/__init__.py
  nonebot/adapters/__init__.py
  nonebot/drivers/__init__.py
  nonebot/drivers/fastapi.py
  nonebot/drivers/quart.py
  nonebot/exception.py
  nonebot/internal/__init__.py
  nonebot/internal/adapter/__init__.py
  nonebot/internal/adapter/adapter.py
  nonebot/internal/adapter/bot.py
  nonebot/internal/adapter/event.py
  nonebot/internal/adapter/message.py
  nonebot/internal/adapter/template.py
  nonebot/internal/driver/__init__.py
  nonebot/internal/driver/driver.py
  nonebot/internal/driver/model.py
  nonebot/internal/matcher.py
  nonebot/internal/params.py
  nonebot/internal/permission.py
  nonebot/internal/rule.py
  nonebot/matcher.py
  nonebot/message.py
  nonebot/params.py
  nonebot/permission.py
  nonebot/rule.py
  nonebot/typing.py
  packages/nonebot-plugin-docs/pyproject.toml
  poetry.lock
  website/docs/tutorial/plugin/matcher-operation.md
  website/src/pages/changelog.md
Labels: enhancement

#775 Plugin: random_cat_gif
  website/static/plugins.json
Labels: Plugin

#777 Plugin: 无数据库的问答插件
  website/static/plugins.json
Labels: Plugin

#779 Plugin: Fgo从者推理
  website/static/plugins.json
Labels: Plugin

#772 Fix `Message.template` format spec does not support static method
  nonebot/internal/adapter/template.py
  tests/test_adapters/test_template.py
  tests/utils.py
Labels: bug

#784 Plugin: 轻量文字转图片插件
  website/static/plugins.json
Labels: Plugin

#782 Bugfix: Potential message body injection vulnerability in `MessageTemplate`
  nonebot/internal/adapter/template.py
  tests/test_adapters/test_template.py
  tests/test_examples/test_weather.py
  tests/utils.py
Labels: bug

#786 Bot: 琪露诺Bot
  website/static/bots.json
Labels: Bot

#788 Plugin: おはよう！
  website/static/plugins.json
Labels: Plugin

#789 Add document for message template
  nonebot/internal/adapter/message.py
  poetry.lock
  tests/test_adapters/test_message.py
  website/docs/tutorial/process-message.md
Labels: documentation

#794 Docs: Add project code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#803 Plugin: pixiv.net p站查询图片
  website/static/plugins.json
Labels: Plugin

#798 Docs: 更新贡献指南
  CONTRIBUTING.md
Labels: documentation

#806 Docs: 修改消息模板文档中错误的样例
  website/docs/tutorial/process-message.md
  website/versioned_docs/version-2.0.0-beta.2/tutorial/process-message.md
Labels: documentation

#810 Plugin: 60s读世界小插件
  website/static/plugins.json
Labels: Plugin

#813 Docs: 减小更新日志 toc 最大显示等级
  website/src/pages/changelog.md
Labels: documentation

#797 Feature: 新增文本完整匹配规则
  nonebot/__init__.py
  nonebot/plugin/__init__.py
  nonebot/plugin/on.py
  nonebot/plugin/on.pyi
  nonebot/rule.py
  tests/test_rule.py
  website/docs/tutorial/plugin/create-matcher.md
Labels: enhancement

#815 Fix: 修复 `on_fullmatch` 返回类型错误
  nonebot/plugin/on.py
Labels: bug

#819 Docs: 修复 ci/cd action 中错误的版本号
  website/docs/tutorial/deployment.md
Labels: documentation

#822 CI: 添加更新日志忽略 label 选项
  .github/release-drafter.yml
Labels: skip-changelog

#826 Chore(deps): bump dependencies
  poetry.lock
Labels: dependencies

#825 Plugin: YetAnotherPicSearch
  website/static/plugins.json
Labels: Plugin

#829 Plugin: 原神抽卡记录分析
  website/static/plugins.json
Labels: Plugin

#830 Docs: 添加对 `fastapi_reload` 在 Windows 平台额外影响的说明
  website/docs/tutorial/choose-driver.md
  website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
Labels: documentation

#832 Plugin: 每日一句
  website/static/plugins.json
Labels: Plugin

#834 Plugin: update nonebot-bison
  website/static/plugins.json
Labels: skip-changelog

#835 :construction_worker: fix ci error when no changlog performed
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#836 :fire: Plugin: 移除 nonebot-general-rss
  website/static/plugins.json
Labels: skip-changelog

#839 Plugin: QQ自动续火花
  website/static/plugins.json
Labels: Plugin

#837 :arrow_up: update fastapi and tomlkit
  poetry.lock
  pyproject.toml
  yarn.lock
Labels: dependencies

#841 Plugin: mockingbird
  website/static/plugins.json
Labels: Plugin
