Repository nonebot/nonebot2, pull requests merged in 2023-06, with the labels that each got.

#2070 Release: v2.0.0
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  nonebot/config.py
  nonebot/log.py
  nonebot/utils.py
  packages/nonebot-plugin-docs/README.md
  poetry.lock
  pyproject.toml
  tests/plugins/metadata.py
  tests/test_plugin/test_load.py
  website/docs/advanced/dependency.mdx
  website/docs/ospp/2021.md
  website/docs/ospp/2022.md
  website/docs/ospp/2023.md
  website/docusaurus.config.js
  website/package.json
  website/sidebars.js
  website/src/theme/FooterCopyright/index.tsx
  website/versioned_docs/version-2.0.0rc4/advanced/dependency.mdx
  website/versioned_docs/version-2.0.0rc4/api/config.md
  website/versioned_docs/version-2.0.0rc4/api/log.md
  website/versioned_docs/version-2.0.0rc4/ospp/2021.md
  website/versioned_docs/version-2.0.0rc4/ospp/2022.md
  website/versioned_docs/version-2.0.0rc4/ospp/2023.md
  website/versioned_sidebars/version-2.0.0rc4-sidebars.json
Labels: dependencies

#2080 Fix: 修复因 loguru 更新导致的启动和关闭日志 name 不正常
  nonebot/log.py
Labels: bug

#2086 Docs: 添加 Villa 适配器到 README
  README.md
Labels: documentation

#2088 Fix: aiohttp 请求时 data 和 file 不能同时存在
  nonebot/drivers/aiohttp.py
  tests/test_driver.py
Labels: bug

#2089 Feature: 依赖注入支持 Generic TypeVar 和 Matcher 重载
  nonebot/internal/params.py
  nonebot/utils.py
  tests/plugins/param/param_bot.py
  tests/plugins/param/param_event.py
  tests/plugins/param/param_matcher.py
  tests/test_param.py
  website/docs/advanced/dependency.mdx
  website/docs/advanced/matcher.md
  website/docs/appendices/overload.md
Labels: enhancement

#2087 Docs: 更新插件元数据的相关描述
  website/docs/advanced/plugin-info.md
Labels: documentation

#2078 Docs: 完成发布插件教程
  website/docs/developer/plugin-publishing.md
  website/docs/developer/plugin-publishing.mdx
Labels: documentation

#2094 Feature: 插件商店适配最新的插件元数据
  .github/ISSUE_TEMPLATE/plugin_publish.yml
  .github/workflows/noneflow.yml
  website/static/plugins.json
Labels: enhancement

#2096 Docs: 微调插件元数据的部分描述
  website/docs/advanced/plugin-info.md
  website/docs/developer/plugin-publishing.mdx
Labels: documentation

#2113 Feature: 添加内置插件的插件元数据
  nonebot/plugins/echo.py
  nonebot/plugins/single_session.py
  packages/nonebot-plugin-docs/README.md
  packages/nonebot-plugin-docs/nonebot_plugin_docs/__init__.py
  packages/nonebot-plugin-docs/pyproject.toml
Labels: enhancement

#2124 Fix: 修复 `ArgParam` 不支持 `Annotated`
  nonebot/internal/params.py
  tests/plugins/param/param_arg.py
  tests/test_param.py
Labels: bug

#2126 Docs: 修复依赖注入文档 `ArgStr` 3.9+ 和 3.8+ 版本代码写反
  website/docs/advanced/dependency.mdx
  website/versioned_docs/version-2.0.0/advanced/dependency.mdx
  website/versioned_docs/version-2.0.0rc4/advanced/dependency.mdx
Labels: documentation

#2127 Feature: 添加用于动态继承支持适配器数据的方法
  nonebot/plugin/__init__.py
  nonebot/plugin/load.py
  tests/plugins/metadata_2.py
  tests/test_plugin/test_load.py
Labels: enhancement

#2140 Docs: 修复日志自定义文档 typo
  website/docs/appendices/log.md
Labels: documentation
