Repository nonebot/nonebot2, pull requests merged in 2023-04, with the labels that each got.

#1870 Release: v2.0.0rc4
  poetry.lock
  pyproject.toml
Labels: dependencies

#1868 Plugin: ROLL
  website/static/plugins.json
Labels: Plugin

#1871 Plugin: 激战2！！！
  website/static/plugins.json
Labels: Plugin

#1874 Plugin: 今日老婆
  website/static/plugins.json
Labels: Plugin

#1876 Plugin: 来份睡眠套餐
  website/static/plugins.json
Labels: Plugin

#1889 Adapter: Walle-Q
  website/static/adapters.json
Labels: Adapter

#1890 Docs: 更新部署文档
  website/docs/best-practice/deployment.mdx
Labels: documentation

#1891 Docs: 添加 Walle-Q 到 Readme
  README.md
Labels: documentation

#1880 Plugin: nonebot_api_paddle
  website/static/plugins.json
Labels: Plugin

#1884 Plugin: AI生成PPT
  website/static/plugins.json
Labels: Plugin

#1887 Plugin: Steam游戏状态播报
  website/static/plugins.json
Labels: Plugin

#1923 Fix: shell command 包含富文本时报错信息出错
  nonebot/rule.py
  tests/test_rule.py
Labels: bug

#1927 Docs: 修正教程中部分 import 缺失的问题
  website/docs/tutorial/event-data.mdx
  website/docs/tutorial/handler.mdx
Labels: documentation

#1928 Docs: 使用 issue 表单替换 issue 模板
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/document.md
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation

#1945 Docs: 开启 blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#1938 Docs: 新增插件跨平台指南
  website/docs/advanced/adapter.md
  website/docs/advanced/dependency.mdx
  website/docs/appendices/overload.md
  website/docs/best-practice/multi-adapter.mdx
  website/docs/best-practice/testing/_category_.json
Labels: documentation

#1951 Feature: 支持主动停止 `none` 系列驱动器
  nonebot/drivers/none.py
Labels: enhancement

#1950 Feature: 支持 `re.Match` 依赖注入
  nonebot/consts.py
  nonebot/params.py
  nonebot/rule.py
  tests/plugins/param/param_state.py
  tests/test_param.py
  tests/test_rule.py
Labels: enhancement, Breaking
