Repository nonebot/nonebot2, pull requests merged in 2023-10, with the labels that each got.

#2381 CI: 修复 Release 权限错误
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#2390 Docs: 修复文档主页 Features 不居中
  website/src/components/Home/Feature.tsx
Labels: documentation

#2387 Docs: 修改商店发布的跳转链接
  website/src/components/Store/Content/Adapter.tsx
  website/src/components/Store/Content/Bot.tsx
  website/src/components/Store/Content/Plugin.tsx
Labels: documentation

#2401 Docs: 更新最佳实践 Alconna
  assets/plugins.json
  website/docs/best-practice/alconna/README.mdx
  website/docs/best-practice/alconna/command.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.md
  website/docs/best-practice/alconna/uniseg.md
  website/docs/best-practice/alconna/utils.md
Labels: documentation

#2424 Docs: 文档启用百度统计
  website/docusaurus.config.js
Labels: documentation

#2419 Feature: 添加多消息段命令解析支持
  nonebot/rule.py
  tests/test_rule.py
Labels: enhancement

#2429 Docs: 修复 Alconna 文档 typo
  website/versioned_docs/version-2.1.0/best-practice/alconna/command.md
  website/versioned_docs/version-2.1.1/best-practice/alconna/command.md
Labels: documentation

#2433 Fix: 修复依赖注入对 Literal 检查报错
  nonebot/utils.py
  tests/test_utils.py
Labels: bug
