Repository nonebot/nonebot2, pull requests merged in 2023-09, with the labels that each got.

#2338 Fix: 修复依赖注入解析类型标注错误
  nonebot/dependencies/__init__.py
  poetry.lock
Labels: bug

#2343 Feature: 补充依赖注入部分情况下类型错误时的日志提示
  nonebot/dependencies/__init__.py
Labels: enhancement

#2349 Docs: 更新最佳实践部分的 Alconna 章节
  website/docs/advanced/matcher.md
  website/docs/best-practice/alconna/README.mdx
  website/docs/best-practice/alconna/command.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.md
  website/docs/best-practice/alconna/utils.md
Labels: documentation

#2351 Feature: 为事件响应器添加更多源码信息
  nonebot/internal/matcher/__init__.py
  nonebot/internal/matcher/matcher.py
  nonebot/matcher.py
  nonebot/plugin/on.py
  nonebot/plugin/on.pyi
  nonebot/utils.py
  tests/.coveragerc
  tests/plugins/matcher/matcher_info.py
  tests/test_matcher/test_matcher.py
Labels: enhancement

#2352 Feature: 为 Matcher.HANDLER_PARAM_TYPES 补增类型
  nonebot/internal/matcher/matcher.py
Labels: enhancement

#2359 Docs: 更新 `get_asgi` 函数的文档字符串
  nonebot/__init__.py
Labels: documentation

#2355 Feature: 优化检查事件响应器的日志
  nonebot/message.py
  tests/test_matcher/test_matcher.py
Labels: enhancement

#2360 Feature: 优先使用 `Annotated` 的最后一个子依赖
  nonebot/internal/params.py
  tests/plugins/param/param_arg.py
  tests/plugins/param/param_depend.py
  tests/test_param.py
Labels: enhancement

#2371 Docs: 增加赞助者显示
  README.md
Labels: documentation

#2374 Fix: bot.call_api 在被 called api hook mock 后应该忽略 exception
  nonebot/internal/adapter/bot.py
  tests/test_adapters/test_bot.py
Labels: bug

#2376 Docs: 修复侧边栏 TOC 在 SSR 模式下的渲染问题
  yarn.lock
Labels: documentation

#2377 Docs: 修复商店搜索信息的错字
  website/src/components/Store/Content/Adapter.tsx
  website/src/components/Store/Content/Driver.tsx
Labels: documentation
