Repository nonebot/nonebot2, pull requests merged in 2023-08, with the labels that each got.

#2237 Docs: 更新最佳实践部分的 Alconna 章节
  website/docs/advanced/matcher.md
  website/docs/best-practice/alconna.md
  website/docs/best-practice/alconna/README.mdx
  website/docs/best-practice/alconna/_category_.json
  website/docs/best-practice/alconna/alconna.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.md
Labels: documentation

#2241 Docs: 修复文档 Last updated author 错误
  .github/workflows/website-deploy.yml
  .github/workflows/website-preview.yml
Labels: documentation

#2255 Docs: 更新贡献指南
  CONTRIBUTING.md
Labels: documentation

#2079 Docs: 适配器编写教程
  website/docs/developer/adapter-writing.md
Labels: documentation

#2275 Docs: 修复文档中错误的标点
  website/docs/tutorial/message.md
  website/versioned_docs/version-2.0.0/tutorial/message.md
  website/versioned_docs/version-2.0.0rc4/tutorial/message.md
  website/versioned_docs/version-2.0.1/tutorial/message.md
Labels: documentation

#2278 Docs: 补充 `get_last_receive` 示例
  website/docs/appendices/session-control.mdx
  website/versioned_docs/version-2.0.0/appendices/session-control.mdx
  website/versioned_docs/version-2.0.0rc4/appendices/session-control.mdx
  website/versioned_docs/version-2.0.1/appendices/session-control.mdx
Labels: documentation

#2279 Docs: 修复子依赖部分代码行号错误
  website/docs/advanced/dependency.mdx
  website/versioned_docs/version-2.0.0/advanced/dependency.mdx
  website/versioned_docs/version-2.0.1/advanced/dependency.mdx
Labels: documentation

#2282 Docs: 修复 Alconna 中 `CommandResult` 描述错误
  website/docs/best-practice/alconna/matcher.md
Labels: documentation

#2284 Fix: 设置 file request 默认 filename
  nonebot/internal/driver/model.py
  tests/test_driver.py
Labels: bug

#2296 Feature: 细化 driver 职责类型
  nonebot/__init__.py
  nonebot/drivers/__init__.py
  nonebot/drivers/aiohttp.py
  nonebot/drivers/fastapi.py
  nonebot/drivers/httpx.py
  nonebot/drivers/quart.py
  nonebot/drivers/websockets.py
  nonebot/internal/adapter/adapter.py
  nonebot/internal/driver/__init__.py
  nonebot/internal/driver/driver.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_adapters/test_adapter.py
  tests/test_driver.py
  tests/test_init.py
  tests/utils.py
  website/docs/advanced/driver.md
  website/docs/advanced/routing.md
  website/docs/developer/adapter-writing.md
Labels: enhancement

#2303 Docs: 更新最佳实践部分的 Alconna 章节
  website/docs/best-practice/alconna/alconna.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.md
  website/docs/best-practice/alconna/utils.md
  website/static/plugins.json
Labels: documentation

#2316 Docs: 添加 Discord 适配器描述，补充 Villa 适配器协议链接
  README.md
Labels: documentation

#2310 Feature: 支持子依赖定义 Pydantic 类型校验
  nonebot/dependencies/__init__.py
  nonebot/dependencies/utils.py
  nonebot/internal/params.py
  tests/plugins/param/param_depend.py
  tests/test_param.py
  website/docs/advanced/dependency.mdx
Labels: enhancement
