Repository nonebot/nonebot2, pull requests merged in 2023-07, with the labels that each got.

#2134 Feature: CommandGroup 支持命令别名添加前缀选项
  nonebot/plugin/on.py
  nonebot/plugin/on.pyi
  tests/plugins/plugin/matchers.py
  tests/test_plugin/test_on.py
  website/docs/advanced/matcher.md
Labels: enhancement

#2143 Fix: 修复 dotenv 配置项为 None 将会跳过赋值
  nonebot/config.py
  tests/.env.test
  tests/test_init.py
Labels: bug

#2154 Feature: 补充响应器组属性
  nonebot/plugin/on.pyi
Labels: enhancement

#2155 Docs: 补充 Message.only 文档
  website/docs/tutorial/message.md
  website/versioned_docs/version-2.0.0/tutorial/message.md
Labels: documentation

#2172 Docs: 格式化钩子函数中的代码片段
  website/docs/advanced/runtime-hook.md
  website/versioned_docs/version-2.0.0/advanced/runtime-hook.md
  website/versioned_docs/version-2.0.0rc4/advanced/runtime-hook.md
Labels: documentation

#2173 Docs: 钩子函数代码片段补充
  website/docs/advanced/runtime-hook.md
  website/versioned_docs/version-2.0.0/advanced/runtime-hook.md
  website/versioned_docs/version-2.0.0rc4/advanced/runtime-hook.md
Labels: documentation

#2192 Fix: 修复 Quart WS task 上下文错误
  nonebot/drivers/quart.py
  tests/test_broadcast.py
  tests/test_driver.py
Labels: bug

#2193 Feature: 使用 `typing.override` 标记
  nonebot/drivers/aiohttp.py
  nonebot/drivers/fastapi.py
  nonebot/drivers/httpx.py
  nonebot/drivers/none.py
  nonebot/drivers/quart.py
  nonebot/drivers/websockets.py
  nonebot/typing.py
  nonebot/utils.py
Labels: enhancement

#2194 Develop: 添加 Pyright 检查
  .github/workflows/pyright.yml
  README.md
  nonebot/plugin/on.pyi
  package.json
  pyproject.toml
  yarn.lock
Labels: enhancement

#2198 Docs: 添加 scoped 插件配置指南
  website/docs/appendices/config.mdx
Labels: documentation

#2205 Docs: 移除商店中不符合现规范的 tag
  website/static/bots.json
  website/static/plugins.json
Labels: documentation

#2208 Docs: 移动 Alconna 文档至最佳实践
  website/docs/advanced/matcher.md
  website/docs/best-practice/alconna.md
  website/static/plugins.json
Labels: documentation

#2209 Release: v2.0.1
  poetry.lock
  pyproject.toml
Labels: dependencies
