Repository nonebot/nonebot2, pull requests merged in 2023-05, with the labels that each got.

#1975 Fix: 修复命令强制空白符影响无参数情况
  nonebot/rule.py
  tests/test_rule.py
Labels: bug

#1980 Docs: 修复获取事件信息文档代码范例中缺失的 import
  website/versioned_docs/version-2.0.0rc4/tutorial/event-data.mdx
Labels: documentation

#1982 Docs: 修复事件处理函数文档代码范例中缺失的 import
  website/versioned_docs/version-2.0.0rc4/tutorial/handler.mdx
Labels: documentation

#1983 Docs: 修复获取事件信息文档代码范例中的高亮行
  website/versioned_docs/version-2.0.0rc4/tutorial/event-data.mdx
Labels: documentation

#2010 Docs: 使用 issue form 进行商店发布
  .github/ISSUE_TEMPLATE/adapter_publish.yml
  .github/ISSUE_TEMPLATE/bot_publish.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/plugin_publish.yml
  website/src/components/Adapter.tsx
  website/src/components/Bot.tsx
  website/src/components/Plugin.tsx
Labels: documentation

#2034 Feature: 移除部分依赖注入参数默认值检查
  nonebot/internal/params.py
  nonebot/utils.py
  tests/plugins/param/priority.py
  tests/test_param.py
Labels: enhancement

#2040 Fix: 修复插件 require 未声明插件会识别为子插件
  nonebot/plugin/load.py
  nonebot/plugin/manager.py
Labels: bug

#2068 Docs: 更新 README 适配器链接
  README.md
Labels: documentation

#2069 Docs: 添加 Alconna 响应器介绍
  website/docs/advanced/matcher.md
Labels: documentation
