Repository nonebot/nonebot2, pull requests merged in 2024-04, with the labels that each got.

#2618 Docs: 添加 `RegexMatched` 依赖注入文档
  website/docs/advanced/dependency.mdx
  website/versioned_docs/version-2.1.3/advanced/dependency.mdx
  website/versioned_docs/version-2.2.0/advanced/dependency.mdx
  website/versioned_docs/version-2.2.1/advanced/dependency.mdx
Labels: documentation

#2619 Fix: 将 aiohttp 的 quote_fields 默认设为 False
  nonebot/drivers/aiohttp.py
Labels: bug

#2623 Docs: 为商店的详情卡片添加跳转链接
  website/src/components/Resource/DetailCard/index.tsx
Labels: documentation

#2628 Docs: 修复 `RegexMatched​` 文档高亮行错误
  website/docs/advanced/dependency.mdx
  website/versioned_docs/version-2.1.3/advanced/dependency.mdx
  website/versioned_docs/version-2.2.0/advanced/dependency.mdx
  website/versioned_docs/version-2.2.1/advanced/dependency.mdx
Labels: documentation

#2626 Docs: 为商店插件卡片添加更多展示内容
  website/src/components/Resource/Card/index.tsx
  website/src/components/Resource/Card/styles.css
  website/src/components/Resource/DetailCard/index.tsx
  website/src/components/Resource/DetailCard/styles.css
  website/src/components/Resource/ValidStatus/index.tsx
  website/src/libs/valid.ts
Labels: documentation

#2640 Docs: 添加 RocketChat 适配器说明
  README.md
Labels: documentation

#2656 Docs: 更新最佳实践的 Alconna 部分
  website/docs/best-practice/alconna/README.mdx
  website/docs/best-practice/alconna/command.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.mdx
  website/docs/best-practice/alconna/uniseg.mdx
Labels: documentation

#2654 Bug: inherit_supported_adapters 在展开缩写前取交集
  nonebot/plugin/load.py
  tests/plugins/metadata_3.py
  tests/test_plugin/test_load.py
Labels: bug

#2660 Docs: 添加 Kritor 适配器说明
  README.md
Labels: documentation

#2661 Docs: 更新 Villa 适配器说明
  README.md
Labels: documentation

#2665 Feature: 嵌套插件名称作用域优化
  nonebot/__init__.py
  nonebot/internal/matcher/matcher.py
  nonebot/plugin/__init__.py
  nonebot/plugin/load.py
  nonebot/plugin/manager.py
  nonebot/plugin/model.py
  nonebot/plugin/on.py
  tests/dynamic/require_not_loaded/__init__.py
  tests/dynamic/require_not_loaded/subplugin1.py
  tests/dynamic/require_not_loaded/subplugin2.py
  tests/plugins/nested/__init__.py
  tests/test_matcher/test_matcher.py
  tests/test_plugin/test_get.py
  tests/test_plugin/test_load.py
  tests/test_plugin/test_manager.py
  tests/test_plugin/test_on.py
Labels: enhancement, Breaking

#2676 Docs: 添加 OSPP 2024 项目说明
  website/docs/ospp/2024.md
Labels: documentation
