Repository nonebot/nonebot2, pull requests merged in 2024-12, with the labels that each got.

#3152 Fix: httpx proxy 与 aiohttp timeout 参数新版本修改
  envs/pydantic-v1/poetry.lock
  envs/pydantic-v2/poetry.lock
  nonebot/drivers/aiohttp.py
  nonebot/drivers/httpx.py
  poetry.lock
  pyproject.toml
Labels: bug

#3158 Docs: 使用勾选框而不是评论来重新测试插件
  website/docs/developer/plugin-publishing.mdx
  website/versioned_docs/version-2.3.1/developer/plugin-publishing.mdx
  website/versioned_docs/version-2.3.2/developer/plugin-publishing.mdx
  website/versioned_docs/version-2.3.3/developer/plugin-publishing.mdx
  website/versioned_docs/version-2.4.0/developer/plugin-publishing.mdx
Labels: documentation

#3155 Feature: 存储 matcher 发送 prompt 的结果
  nonebot/consts.py
  nonebot/internal/matcher/matcher.py
  nonebot/internal/params.py
  nonebot/params.py
  tests/plugins/param/param_arg.py
  tests/plugins/param/param_matcher.py
  tests/test_param.py
  website/docs/advanced/dependency.mdx
Labels: enhancement

#3197 Docs: 添加 localstore 插件配置
  website/docs/best-practice/data-storing.md
  website/versioned_docs/version-2.3.1/best-practice/data-storing.md
  website/versioned_docs/version-2.3.2/best-practice/data-storing.md
  website/versioned_docs/version-2.3.3/best-practice/data-storing.md
  website/versioned_docs/version-2.4.0/best-practice/data-storing.md
Labels: documentation
