Repository nonebot/nonebot2, pull requests merged in 2024-10, with the labels that each got.

#3053 Feature: 迁移至结构化并发框架 AnyIO
  envs/pydantic-v1/poetry.lock
  envs/pydantic-v2/poetry.lock
  envs/test/poetry.lock
  envs/test/pyproject.toml
  nonebot/dependencies/__init__.py
  nonebot/drivers/none.py
  nonebot/internal/adapter/bot.py
  nonebot/internal/driver/_lifespan.py
  nonebot/internal/driver/abstract.py
  nonebot/internal/matcher/matcher.py
  nonebot/internal/params.py
  nonebot/internal/permission.py
  nonebot/internal/rule.py
  nonebot/message.py
  nonebot/plugin/load.py
  nonebot/typing.py
  nonebot/utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_adapters/test_adapter.py
  tests/test_adapters/test_bot.py
  tests/test_broadcast.py
  tests/test_compat.py
  tests/test_config.py
  tests/test_driver.py
  tests/test_echo.py
  tests/test_init.py
  tests/test_matcher/test_matcher.py
  tests/test_matcher/test_provider.py
  tests/test_param.py
  tests/test_permission.py
  tests/test_plugin/test_get.py
  tests/test_plugin/test_load.py
  tests/test_plugin/test_manager.py
  tests/test_plugin/test_on.py
  tests/test_rule.py
  tests/test_single_session.py
  website/docs/README.md
Labels: enhancement

#3084 Fix: 修复结构化并发子依赖取消缓存问题
  nonebot/dependencies/__init__.py
  nonebot/internal/params.py
  tests/plugins/param/param_depend.py
  tests/test_param.py
Labels: bug

#3095 Feature: 跳过部分非必要的 task group 创建
  nonebot/dependencies/__init__.py
  nonebot/internal/driver/abstract.py
Labels: enhancement

#3062 Docs: 修复侧边栏滚动
  yarn.lock
Labels: documentation

#3087 Docs: 新增 nonebug 新版启动需要的配置
  website/docs/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.1/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.2/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.3/best-practice/testing/README.mdx
Labels: documentation

#3097 Release: v2.4.0
  .pre-commit-config.yaml
  envs/pydantic-v1/poetry.lock
  envs/pydantic-v2/poetry.lock
  envs/test/poetry.lock
  poetry.lock
  pyproject.toml
Labels: dependencies
