Repository nonebot/nonebot2, pull requests merged in 2024-02, with the labels that each got.

#2558 Docs: 修复表单标签状态更新
  website/src/components/Form/Items/Tag/index.tsx
Labels: documentation

#2563 Feature: 添加插件 Pydantic 相关使用方法
  nonebot/__init__.py
  nonebot/compat.py
  nonebot/plugin/__init__.py
  tests/.env.test
  tests/test_compat.py
  tests/test_plugin/test_get.py
  website/docs/appendices/config.mdx
  website/docs/developer/adapter-writing.md
  website/docs/tutorial/application.md
  website/docs/tutorial/message.md
Labels: enhancement

#2566 Docs: 添加产品赞助列表
  README.md
Labels: documentation

#2568 Docs: 更新 Alconna 文档
  website/docs/best-practice/alconna/command.md
  website/docs/best-practice/alconna/config.md
  website/docs/best-practice/alconna/matcher.md
  website/docs/best-practice/alconna/uniseg.mdx
  website/docs/best-practice/alconna/utils.md
Labels: documentation

#2570 Docs: 添加适配器测试注意事项
  website/docs/developer/adapter-writing.md
Labels: documentation

#2572 Fix: `Message.__contains__()` 未考虑 `bool(MessageSegment)` 存在 False 情况导致的异常结果
  nonebot/internal/adapter/message.py
  tests/test_adapters/test_message.py
Labels: bug

#2577 Fix: 修改遗漏的过时 Pydantic 方法
  nonebot/__init__.py
  nonebot/compat.py
  nonebot/drivers/fastapi.py
  nonebot/drivers/quart.py
  website/docs/appendices/rule.md
  website/docs/developer/adapter-writing.md
Labels: bug

#2579 Feature: 优化 pydantic 兼容函数 `model_dump` 和 `type_validate_json`
  nonebot/compat.py
  tests/test_compat.py
Labels: enhancement

#2585 Docs: 更新 Session Expire Timeout​ 文档
  nonebot/config.py
  website/docs/appendices/config.mdx
Labels: documentation
