Repository nonebot/nonebot2, pull requests merged in 2024-11, with the labels that each got.

#3098 Docs: 修复 changelog 链接
  website/docusaurus.config.ts
  yarn.lock
Labels: documentation

#3100 Docs: Changelog 按页码挂载 route
  website/docusaurus.config.ts
  website/sidebars.ts
  website/versioned_sidebars/version-2.3.3-sidebars.json
  website/versioned_sidebars/version-2.4.0-sidebars.json
  yarn.lock
Labels: documentation

#3101 Docs: 修复侧边栏折叠状态问题
  yarn.lock
Labels: documentation

#3106 Docs: 修复 wwads 造成的 client 水合不匹配
  website/src/theme/Page/TOC/Container/index.tsx
Labels: documentation

#3110 Feature: 提升已加载的适配器日志等级
  nonebot/internal/driver/abstract.py
Labels: enhancement

#3124 Security: restrict workflow context
  .github/workflows/website-preview-cd.yml
  .github/workflows/website-preview-ci.yml
Labels: skip-changelog, github_actions

#3127 CI: 使用最新版的 NoneFlow
  .github/workflows/noneflow.yml
  assets/adapters.json5
  assets/bots.json5
  assets/drivers.json5
  assets/plugins.json5
Labels: skip-changelog

#3130 CI: 更新 assets/plugins.json5 文件里的 project_link 字段
  assets/plugins.json5
Labels: skip-changelog

#3134 Docs: 添加 Mail 适配器说明
  README.md
Labels: documentation

#3135 Docs: 移除侧栏遮罩及启用构建加速
  website/babel.config.js
  website/docusaurus.config.ts
  website/package.json
  yarn.lock
Labels: documentation

#3138 CI: 添加 codecov junit result report
  .github/workflows/codecov.yml
  scripts/run-tests.sh
Labels: skip-changelog

#3137 Fix: 屏蔽 pydantic 2.10.0
  envs/pydantic-v1/poetry.lock
  envs/pydantic-v2/poetry.lock
  envs/test/poetry.lock
  envs/test/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: bug

#3136 Docs: 添加 pytest-asyncio 配置
  website/docs/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.1/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.2/best-practice/testing/README.mdx
  website/versioned_docs/version-2.3.3/best-practice/testing/README.mdx
  website/versioned_docs/version-2.4.0/best-practice/testing/README.mdx
Labels: documentation
